[tox]
envlist = py{310,311,312,313,314,315}
skip_missing_interpreters = true

[testenv]
deps =
    -rrequirements.txt
    pytest
    pytest-asyncio
    pytest-cov
commands =
    pytest --cov-report=xml --cov=greeclimate tests/
